name: E2E Cypress tests
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Cypress E2E tests
    runs-on: ubuntu-latest
    env:
      # prevents extra Cypress installation progress messages
      CI: 1
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          # TODO: Parse this from index management plugin
          java-version: 14
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: index-management
          # TODO: Move this after OpenSearch-Dashboards plugin setup so we can pull down the correct branch to support all opendistro branches
          repository: opendistro-for-elasticsearch/index-management
      - name: Run elasticsearch with plugin
        run: |
          cd index-management
          ./gradlew run &
          sleep 300
        # timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9200)" != "200" ]]; do sleep 5; done'
      - name: Checkout Index Management Dashboards plugin
        uses: actions/checkout@v2
        with:
          path: index-management-dashboards-plugin
      - name: Get OpenSearch-Dashboards version
        id: opensearch_dashboards_version
        run: |
          echo "::set-output name=opensearch_dashboards_version::$(node -p "(require('./index-management-dashboards-plugin/opensearch_dashboards.json').opensearchDashboardsVersion).match(/[.0-9]+/)[0]")"
      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ steps.opensearch_dashboards_version.outputs.opensearch_dashboards_version }}
          token: ${{ secrets.GITHUB_OPENSEARCH_DASHBOARDS_OSS }}
          path: OpenSearch-Dashboards
      - name: Get node and yarn versions
        id: versions
        run: |
          echo "::set-output name=node_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.node).match(/[.0-9]+/)[0]")"
          echo "::set-output name=yarn_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.yarn).match(/[.0-9]+/)[0]")"
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install correct yarn version for OpenSearch-Dashboards
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions.outputs.yarn_version }}
      - name: Bootstrap plugin/OpenSearch-Dashboards
        run: |
          mkdir -p OpenSearch-Dashboards/plugins
          mv index-management-dashboards-plugin OpenSearch-Dashboards/plugins
          cd OpenSearch-Dashboards/plugins/index-management-dashboards-plugin
          yarn osd bootstrap
      - name: Run OpenSearch-Dashboards server
        run: |
          cd OpenSearch-Dashboards
          yarn start --no-base-path --no-watch &
          sleep 300
        # timeout 300 bash -c 'while [[ "$(curl -s localhost:5601/api/status | jq -r '.status.overall.state')" != "green" ]]; do sleep 5; done'
      # for now just chrome, use matrix to do all browsers later
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: OpenSearch-Dashboards/plugins/index-management-dashboards-plugin
          command: yarn run cypress run
          wait-on: 'http://localhost:5601'
          browser: chrome
      # Screenshots are only captured on failure, will change this once we do visual regression tests
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: OpenSearch-Dashboards/plugins/index-management-dashboards-plugin/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: OpenSearch-Dashboards/plugins/index-management-dashboards-plugin/cypress/videos
