name: Unit tests workflow
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Index Management Dashboards plugin
        uses: actions/checkout@v2
        with:
          path: index-management-dashboards-plugin
      - name: Get OpenSearch-Dashboards version
        id: opensearch_dashboards_version
        run: |
          echo "::set-output name=opensearch_dashboards_version::$(node -p "(require('./index-management-dashboards-plugin/opensearch_dashboards.json').opensearchDashboardsVersion).match(/[.0-9]+/)[0]")"
      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ steps.opensearch_dashboards_version.outputs.opensearch_dashboards_version }}
          token: ${{ secrets.GITHUB_OPENSEARCH_DASHBOARDS_OSS }}
          path: OpenSearch-Dashboards
      - name: Get node and yarn versions
        id: versions
        run: |
          echo "::set-output name=node_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.node).match(/[.0-9]+/)[0]")"
          echo "::set-output name=yarn_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.yarn).match(/[.0-9]+/)[0]")"
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install correct yarn version for OpenSearch-Dashboards
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions.outputs.yarn_version }}
      - name: Bootstrap plugin/OpenSearch-Dashboards
        run: |
          mkdir -p OpenSearch-Dashboards/plugins
          mv index-management-dashboards-plugin OpenSearch-Dashboards/plugins
          cd OpenSearch-Dashboards/plugins/index-management-dashboards-plugin
          yarn osd bootstrap
      - name: Run tests
        run: |
          cd OpenSearch-Dashboards/plugins/index-management-dashboards-plugin
          yarn run test:jest
